// VehicleData.js

export const vehicleLocations = [
    {
      id: 1,
      lat: 20.983354,
      lng: 105.809245,
      info: "Thông tin xe 1",
      type: "Xe tải",
      driver: {
        name: "Nguyễn Văn A",
        age: 35,
        license: "B2",
        experience: "10 năm",
      },
      cargoType: "Thư từ",
      departureTime: "08:00 AM",
      totalDistance: "120 km",
      status: "Đang vận chuyển",
      fuelLevel: "75%",
      lastMaintenance: "01/09/2024",
      route: "Hà Nội - Hải Phòng",
      speed: "60 km/h",
    },
    {
      id: 2,
      lat: 20.982643,
      lng: 105.793327,
      info: "Thông tin xe 2",
      type: "Xe container",
      driver: {
        name: "Trần Thị B",
        age: 42,
        license: "FC",
        experience: "15 năm",
      },
      cargoType: "Thực phẩm",
      departureTime: "07:30 AM",
      totalDistance: "200 km",
      status: "Đã giao hàng",
      fuelLevel: "60%",
      lastMaintenance: "15/08/2024",
      route: "Hà Nội - Đà Nẵng",
      speed: "0 km/h",
    },
    {
      id: 3,
      lat: 20.991612,
      lng: 105.781104,
      info: "Thông tin xe 3",
      type: "Xe tải",
      driver: {
        name: "Phạm Văn C",
        age: 28,
        license: "C",
        experience: "5 năm",
      },
      cargoType: "Thiết bị điện tử",
      departureTime: "09:00 AM",
      totalDistance: "150 km",
      status: "Đang nghỉ",
      fuelLevel: "85%",
      lastMaintenance: "05/09/2024",
      route: "Hà Nội - Lào Cai",
      speed: "0 km/h",
    },
    {
      id: 4,
      lat: 21.026688,
      lng: 105.798293,
      info: "Thông tin xe 4",
      type: "Xe tải",
      driver: {
        name: "Lê Thị D",
        age: 30,
        license: "D",
        experience: "8 năm",
      },
      cargoType: "Vật liệu xây dựng",
      departureTime: "06:00 AM",
      totalDistance: "180 km",
      status: "Đang vận chuyển",
      fuelLevel: "50%",
      lastMaintenance: "20/08/2024",
      route: "Hà Nội - Thanh Hóa",
      speed: "70 km/h",
    },
    {
      id: 5,
      lat: 21.034844,
      lng: 105.839387,
      info: "Thông tin xe 5",
      type: "Xe container",
      driver: {
        name: "Đỗ Văn E",
        age: 40,
        license: "E",
        experience: "12 năm",
      },
      cargoType: "Hàng hóa công nghiệp",
      departureTime: "05:30 AM",
      totalDistance: "250 km",
      status: "Đang vận chuyển",
      fuelLevel: "40%",
      lastMaintenance: "10/09/2024",
      route: "Hà Nội - Sài Gòn",
      speed: "80 km/h",
    },
  ];
  